### ISSUE TITLE
node vs nodejs code execution #node version bug

### ISSUE THREAD

**Issue by elissandro13** [elissandro13/URI-code-downloader-script#1]
In my local machine the script is only running with with the nodejs command. This is probably related to the node version.

(node:71188) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array
    at Object.writeFileSync (fs.js:1460:5)
    at buildIdList (/home/elissandro/Desktop/URI-code-downloader-script/index.js:104:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async scrape (/home/elissandro/Desktop/URI-code-downloader-script/index.js:24:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:71188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:71188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by elissandro13** [comment]
node -v v14.15.1
nodejs -v v10.19.0
